import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../data/models/report_model.dart';

class PdfGenerator {
  static Future<String> saveReportAsPDF(Report report) async {
    final pdf = pw.Document();

    final fontData = await rootBundle.load('assets/fonts/NotoSansJP-VariableFont_wght.ttf');
    final notoSansJP = pw.Font.ttf(fontData.buffer.asByteData());

    final now = DateTime.now();
    final formattedDate = "${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}";

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) => pw.DefaultTextStyle(
          style: pw.TextStyle(font: notoSansJP, fontSize: 12),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Column(
                  children: [
                    pw.Text("Laporan Pasien", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 4),
                    pw.Text("利用者のレポート", style: pw.TextStyle(fontSize: 18)),
                  ],
                ),
              ),
              pw.SizedBox(height: 10),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 20),
              _buildRow("Nama Petugas スタッフの名前", report.namaPetugas, notoSansJP),
              _buildRow("Nama Pasien 利用者の名前", report.namaPasien, notoSansJP),
              _buildRow("Tanggal 日付", report.tanggal, notoSansJP),
              pw.SizedBox(height: 20),

              // 🔹 Input
              pw.Text("Input Report 入力レポート:", style: _sectionTitleStyle(notoSansJP)),
              pw.SizedBox(height: 8),
              pw.Text(report.inputReport.isNotEmpty ? report.inputReport : "-", style: _contentStyle(notoSansJP)),
              pw.SizedBox(height: 20),

              // 🔹 Translated
              pw.Text("Translated Report 翻訳されたレポート:", style: _sectionTitleStyle(notoSansJP)),
              pw.SizedBox(height: 8),
              pw.Text(
                report.translatedReport.isNotEmpty ? report.translatedReport : "-",
                style: _contentStyle(notoSansJP).copyWith(fontSize: 13),
              ),
              pw.SizedBox(height: 20),

              pw.Divider(thickness: 1),
              pw.SizedBox(height: 12),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  "Generated by Nindogo! on $formattedDate",
                  style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    final safeNama = report.namaPasien.replaceAll(RegExp(r'[^\w\s]+'), '').replaceAll(' ', '_');
    final safeTanggal = report.tanggal.replaceAll(RegExp(r'[^\d\-]'), '');
    final fileName = (safeNama.isEmpty
        ? "report_${DateTime.now().millisecondsSinceEpoch}"
        : "report_${safeNama}_$safeTanggal") + ".pdf";

    final tempDir = await getTemporaryDirectory();
    final filePath = "${tempDir.path}/$fileName";
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    return filePath;
  }

  static pw.Widget _buildRow(String label, String value, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 120,
            child: pw.Text(
              "$label:",
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, font: font),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value.isNotEmpty ? value : "-", style: _contentStyle(font)),
          ),
        ],
      ),
    );
  }

  static pw.TextStyle _sectionTitleStyle(pw.Font font) => pw.TextStyle(
    fontWeight: pw.FontWeight.bold,
    fontSize: 14,
    font: font,
  );

  static pw.TextStyle _contentStyle(pw.Font font) => pw.TextStyle(
    fontSize: 12,
    font: font,
  );
}
