import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import '../data/models/report_model.dart';

class PdfGenerator {
  static Future<String> saveReportAsPDF(Report report) async {
    final pdf = pw.Document();

    // ✅ Load NotoSansJP font
    final fontData = await rootBundle.load('assets/fonts/NotoSansJP-VariableFont_wght.ttf');
    final notoSansJP = pw.Font.ttf(fontData.buffer.asByteData());

    final generatedDate = DateTime.now();
    final formattedDate = "${generatedDate.year}-${generatedDate.month.toString().padLeft(2, '0')}-${generatedDate.day.toString().padLeft(2, '0')}";

    // ✅ Generate PDF layout
    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) => pw.DefaultTextStyle(
          style: pw.TextStyle(font: notoSansJP, fontSize: 12),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Text(
                  "Laporan Pasien",
                  style: pw.TextStyle(
                    font: notoSansJP,
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.SizedBox(height: 10),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 20),
              _buildRow("Nama Petugas 担当者の名前", report.namaPetugas, notoSansJP),
              _buildRow("Nama Pasien 患者の名前", report.namaPasien, notoSansJP),
              _buildRow("Tanggal 日付", report.tanggal, notoSansJP),
              pw.SizedBox(height: 20),
              pw.Text("Input Report 入力レポート:", style: _sectionTitleStyle(notoSansJP)),
              pw.SizedBox(height: 8),
              pw.Text(report.inputReport, style: _contentStyle(notoSansJP)),
              pw.SizedBox(height: 20),
              pw.Text("Translated Report 翻訳されたレポート:", style: _sectionTitleStyle(notoSansJP)),
              pw.SizedBox(height: 8),
              pw.Text(
                report.translatedReport,
                style: _contentStyle(notoSansJP).copyWith(fontSize: 13),
              ),
              pw.SizedBox(height: 16),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 12),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  "Generated by Akuma-13 on $formattedDate",
                  style: pw.TextStyle(font: notoSansJP, fontSize: 10, fontStyle: pw.FontStyle.italic),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    // ✅ Sanitize filename
    final safeNama = report.namaPasien.replaceAll(RegExp(r'[^\w\s]+'), '').replaceAll(' ', '_');
    final safeTanggal = report.tanggal.replaceAll(RegExp(r'[^\d\-]'), '');
    final fallbackName = "report_${DateTime.now().millisecondsSinceEpoch}.pdf";
    final fileName = safeNama.isEmpty ? fallbackName : "report_${safeNama}_$safeTanggal.pdf";

    // ✅ Save ke folder Download (Android only)
    Directory? downloadDir;
    if (Platform.isAndroid) {
      final status = await Permission.storage.request();
      if (status.isGranted) {
        downloadDir = Directory('/storage/emulated/0/Download');
      }
    }

    downloadDir ??= await getApplicationDocumentsDirectory();
    final file = File("${downloadDir.path}/$fileName");
    await file.writeAsBytes(await pdf.save());

    return file.path;
  }

  static pw.Widget _buildRow(String label, String value, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 120,
            child: pw.Text(
              "$label:",
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, font: font),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: _contentStyle(font)),
          ),
        ],
      ),
    );
  }

  static pw.TextStyle _sectionTitleStyle(pw.Font font) => pw.TextStyle(
    fontWeight: pw.FontWeight.bold,
    fontSize: 14,
    font: font,
  );

  static pw.TextStyle _contentStyle(pw.Font font) => pw.TextStyle(
    fontSize: 12,
    font: font,
  );
}
